### PR TITLE
Add Jenkinsfile for new build pipeline. Copied from hk2-extra

### LINKED ISSUE #452: Jenkins is not building master
Jenkins is building the EE4J_8 branch we need a job that also builds master branch

### PR DESCRIPTION
**Pull request by smillidge**
fixes #452 
Signed-off-by: smillidge <steve.millidge@payara.fish>

### CODE REVIEW

**Comment by romain-grecourt** [comment]
I see that the multi-branch pipeline does polling instead of using a webhook, should I go ahead and create a webhook / disable polling ?

**Comment by smillidge** [comment]
Feel free as I don't really know what I'm doing!

**Comment by smillidge** [comment]
@romain-grecourt are you happy if I delete the old job once this new one is in place and working?

**Comment by romain-grecourt** [comment]
I'd be quite happy to have the old job removed !

**Comment by romain-grecourt** [comment]
I've renamed the job and setup the webhook.

**Comment by romain-grecourt** [comment]
I went ahead and delete the old hk2-build job ; thanks for doing this :)

**Comment by smillidge** [comment]
How did you setup the webhook? I can't see where you can configure this.

**Comment by romain-grecourt** [comment]
Github repository settings / webhooks.

**Comment by smillidge** [comment]
On GitHub or Jenkins?

**Comment by romain-grecourt** [comment]
On GitHub

**Comment by smillidge** [comment]
Ah I don't have permissions to see the settings for the repo. I thought only Eclipse people could see that!

**Comment by romain-grecourt** [comment]
Yes this requires admin privileges.
I inherited some increased privileges on both Jenkins and GitHub while doing some of the ground work on the infra.

**Pull request merged**
