### PR TITLE
Implement a `@Provides` annotation

### LINKED ISSUE #240: Allow for a CDI style @Produces feature
While Factories are ok for having user created stuff, @Produces is more convenient in many cases simply because you generally do not need to create a whole new service just to have code the produces some service or another.

This question on stack-exchange also asked for such a feature:

[http://stackoverflow.com/questions/22856997/hk2-equivalent-of-provides-in-guice-for-jersey-2](http://stackoverflow.com/questions/22856997/hk2-equivalent-of-provides-in-guice-for-jersey-2)

### PR DESCRIPTION
**Pull request by michaelhixson**
Fixes #240

Adds a `@Provides` implementation to `hk2-extras`.  This annotation is similar to [CDI's `@Produces`](https://docs.oracle.com/javaee/7/api/javax/enterprise/inject/Produces.html), [Guice's `@Provides`](https://github.com/google/guice/wiki/ProvidesMethods), and [Spring's `@Bean`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/Bean.html).

Adds three new public types to one new package, [`org.glassfish.hk2.extras.provides`](https://github.com/michaelhixson/glassfish-hk2/tree/add-provides-annotation/hk2-extras/src/main/java/org/glassfish/hk2/extras/provides).
* [`Provides`](https://github.com/michaelhixson/glassfish-hk2/blob/add-provides-annotation/hk2-extras/src/main/java/org/glassfish/hk2/extras/provides/Provides.java) - the annotation that users would apply to their service providers.
* [`ProvidesListener`](https://github.com/michaelhixson/glassfish-hk2/blob/add-provides-annotation/hk2-extras/src/main/java/org/glassfish/hk2/extras/provides/ProvidesListener.java) - the `DynamicConfigurationListener` that users would register to enable the `@Provides` annotation.
* [`NoInstancesFilter`](https://github.com/michaelhixson/glassfish-hk2/blob/add-provides-annotation/hk2-extras/src/main/java/org/glassfish/hk2/extras/provides/NoInstancesFilter.java) - an optional feature that allows users to register classes that have static `@Provides` methods and/or fields, but which otherwise are not meant to be auto-constructed as services.

### CODE REVIEW

**Comment by michaelhixson** [comment]
Assuming that the overall API and design of the feature is on point, there are a few specific topics where I'd like feedback.
1. Is `@Provides` explained well enough in its javadoc, or does it need a more thorough user guide?
2. Is `@Provides(disposeMethod = ...)` the right way to handle disposal of the provided service, or is there another approach that's better (such as CDI's `@Disposes` annotation)?
3. Does `NoInstancesFilter` pull its weight, or should I remove it?  (Is it clear why it's there at all?)

I'm happy to hear feedback about anything else in this PR too, of course.

I avoided changing any existing code in this PR, but there are a couple of things that probably should change.
* Allow`@ContractsProvided` to target methods and fields.  That way there is no need for the `@Provides(contracts = ...)` attribute.
* Allow `@PerLookup` and other scope annotations to target fields.  Otherwise, users may be forced to use a `@Provides` method when they otherwise wanted to use a field just so that they can use that scope annotation.

**Comment by smillidge** [comment]
Thanks for the PR I've requested review by a bunch of committers

**Comment by michaelhixson** [comment]
> You should add a license to your code like the existing code.

@hs536 Do you know which company should be named in the copyright notice?  Most of the existing files name Oracle, but I'm wondering if that no longer applies after the EE4J transition.

I'm assuming you're talking about the [header comments in the source files like this](https://github.com/eclipse-ee4j/glassfish-hk2/blob/48dcd4a68297ba2924eb0d778e7578fbef855ca3/hk2-extras/src/main/java/org/glassfish/hk2/extras/events/DefaultTopicDistributionErrorService.java#L1-L15).

**Comment by hs536** [comment]
@michaelhixson If this is the code you wrote as a member of a company, I think it should be the name of that company. If the code is written as an individual, I think it should be as follows:
````
Copyright (c) 2020 user<user@example.com>. All rights reserved.
````
I searched for the document, but I couldn't find any clear rules about copyright...
  
@smillidge Is my understanding correct?

**Comment by michaelhixson** [comment]
@hs536 Sounds good.  I put my company name to the copyright notice.

**Comment by michaelhixson** [comment]
@smillidge Is there anything else I can do to help move this forward?

**Pull request merged**
