### PR TITLE
Switch namespace usage from javax to jakarta

### PR DESCRIPTION
**Pull request by Cousjava**
For Jakarta EE 9.

### CODE REVIEW

**Comment by smillidge** [comment]
@Cousjava are you witing for anything here. We will need an RC for GlassFish 6

**Comment by Cousjava** [comment]
@smillidge Currently build tests are failing due to pax-exam which is used for some of them not working due to use of javax.inject

**Comment by smillidge** [comment]
What's pax-exam?

**Comment by Cousjava** [comment]
pax-exam is the library used for the OSGi adapter tests, see https://github.com/eclipse-ee4j/glassfish-hk2/blob/master/osgi/adapter-tests/osgi-adapter-test/pom.xml. In particular https://github.com/ops4j/org.ops4j.pax.exam2/blob/master/core/pax-exam-extender-service/src/main/java/org/ops4j/pax/exam/raw/extender/intern/ServiceInjector.java from pax-exam uses javax.inject to run the tests.

**Comment by arjantijms** [comment]
@Cousjava @smillidge How do you feel about disabling the pax-exam based tests for now?

Once everything is integrated we can take a look at that one again then.

**Comment by smillidge** [comment]
I don't think GlassFish uses the OSGI adapter so I don't have a problem. I suppose longer term we need to either decide to poke the pax team (if still active) to update to the jakarta namespace which may mean they have to poke the OSGI people to update to the jakarta namespace or we use a different test technology. The ripples from the jakarta namespace change are large.

**Comment by arjantijms** [comment]
>  The ripples from the jakarta namespace change are large.

That's the major issue yes. If you keep following those ripples you may end up a far way from home, which here is the GF release itself.

**Comment by smillidge** [comment]
Will shading work to move forward rather than disabling?

**Comment by arjantijms** [comment]
989 files is pretty big to look at in detail, but I spot checked it and on the surface it looks good. I also know Jonathan is experienced with HK2, so I'm trusting this is okay.

**Pull request merged**
