### PR TITLE
Fix child service locator shutdown

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: Jan Supol <jan.supol@oracle.com>

### CODE REVIEW

**Comment by jansupol** [comment]
The modified test throws
> java.util.ConcurrentModificationException  at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:806) at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839) at org.jvnet.hk2.internal.ServiceLocatorImpl.shutdown(ServiceLocatorImpl.java:875)

without the fix.

**Comment by romain-grecourt** [comment]
I'm not feeling confident with this change, will let other chime in.

**Comment by arjantijms** [comment]
At first sight, this only works when all other clients of `children` that modify it use `synchronized` as well. 
Not sure what exactly causes the original `ConcurrentModificationException` exactly, but at a glance (without having studied the code further) I wonder why children are seemingly being added while a shutdown is in progress.

**Comment by jansupol** [comment]
The actual fix is to call `childIterator.remove();`. The ConcurrentModificationException is thrown since the ` child.shutdown();` calls ` parent.removeChild(this);` which modifies the `children` array. The synchronized block is there since the loop works with `children` object and other threads use the synchronized block to access it, too, so it, for instance, ensures the caches are not used.

**Pull request merged**
