### PR TITLE
Removed asm repackaging

### PR DESCRIPTION
**Pull request by mulderbaba**

### CODE REVIEW

**Comment by romain-grecourt** [comment]
This will have an impact on GlassFish, integration with GlassFish needs to be tested before merging.

**Comment by Cousjava** [comment]
@mulderbaba You need to sign the ECA (https://www.eclipse.org/legal/ECA.php) and sign-off your commit (git commit -s)

**Comment by smillidge** [comment]
This will require changes to GlassFish but I vote we merge this in and then make the changes when integrating HK2 2.6 to GlassFish.

What do others think?

**Comment by gotojava** [comment]
@mulderbaba can you please resolve the conflicts ?

**Pull request merged**
