### PR TITLE
#559 Race condition when initializing ClassAnalyzer with CdiInjecteeS…

### PR DESCRIPTION
**Pull request by nhenneaux**
…kippingClassAnalyzer

### CODE REVIEW

**Comment by dmatej** [comment]
Hmmm, all accesses to the HashMap were synchronized, so I don't believe the concurrent map will help. But you are probably near - the race condition is outside the synchronisation, one thread should initialize the analyzer and another should find it, but the second is faster (and grabs the lock first).
I'm afraid the fix will not be so simple ...

**Comment by nhenneaux** [comment]
The HashMap content might not be visible to other core LX caches even if the access are synchronized. However you are probably right, it's most probably the order. What about forcing the initit analyser if the map is empty?

**Comment by nhenneaux** [comment]
Hi @dmatej 
do you think you'll be able to review this MR? I could force re-init each time an analyzer is needed?

**Comment by dmatej** [comment]
It would be good to start with clear reliable reproducer right in HK2 tests, perhaps I would be able to get to it in the end of this week if you cannot do it.
But there is also a possibility that the issue is in a way how jetty/jersey initializes. At this moment I don't know which part is responsible for correct initialization (but same as you I would expect it should ensure it HK2). 
When I look at your stacktrace it doesn't look much complicated, I should be able to reproduce it with a unit test. At least with some probability.

**Comment by nhenneaux** [comment]
Hi David,

I tried simple reproduction but so far without success to have something
consistent excepting when running the whole application for which we have a
problem.

The application is listening to two ports (service & admin, using two
server connector within Jetty server). During Jetty startup it triggers
some CDI beans managing lifecycle of the application within a CDI
singleton. Not sure it is related but it perhaps ring a bell on your side.

This issue was not happening in the past but not sure exactly when it
started. One year ago for sure it was fine using Jersey 2 latest at that
time but not sure it started when it moved to Jersey 3.

Best regards,

Nicolas Henneaux

**Comment by dmatej** [comment]
I will try it in some two weeks too, I believe you provided enough information, but if I would need a help, I will send you a message.
I expect I will be able to reproduce it or we will document a way how to use it to avoid issues, not sure now. I'm working on GlassFish tests now and there is a lot of "white spaces". For sure - which exact version of HK2, Jersey and Jetty do you use?

**Comment by nhenneaux** [comment]
Thanks for that!

Jersey 3.0.2, Weld 4.0.2.Final, Jetty 11.0.6 with Java 16

**Comment by loewe** [comment]
Any news on that bug? I can reproduce it with a heavy Payara application when running our load test against it.

**Comment by dmatej** [comment]
This might be interesting for you: [#963 ](https://github.com/eclipse-ee4j/glassfish-hk2/pull/963#issuecomment-1903894425). It seems we are closing to the real solution for the reproducible bug.

**Comment by nhenneaux** [comment]
I'm not sure #963 would help since it is most probably a publishing issue related to usage of non-thread safe data structure even if accessed in synchronized blocks it is not enough to guarantee consistency in multi-threads calls.

**Comment by avpinchuk** [comment]
Hi, @nhenneaux!

Can you try with [this patch](https://github.com/eclipse-ee4j/glassfish-hk2/pull/971)?

**Comment by nhenneaux** [comment]
Hi @avpinchuk 
Thanks for looking into that! 
This error is not happening a lot as it is a race condition somewhere, perhaps 1 build over 100. I don't really want to impact all the services I maintain to try to reproduce eventually. I understand it would be way easier to have a clear reproducer.

Perhaps you can ask on the issue https://github.com/eclipse-ee4j/glassfish-hk2/issues/559

**Comment by dmatej** [comment]
I will close this PR for now, I optimistically expect that all race conditions were fixed by #971 . If not, I would still like to see a reproducer or at least some logical description how it can happen and how provided fix fixes the problem.

**Comment by nhenneaux** [comment]
Hi @dmatej 
It is still happening. Jersey v3.1.3.
```
jakarta.ws.rs.ProcessingException: 
 A MultiException has 1 exceptions.  They are:
 1. java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
 
 	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:312)
 	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687)
 	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
 	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
 	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
 	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
 	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686)
 	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:461)
 	at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:270)
 	at jdk.proxy2/jdk.proxy2.$Proxy164.cancel(Unknown Source)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
 Caused by: A MultiException has 1 exceptions.  They are:
 1. java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
 
 	at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65)
 	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:970)
 	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1014)
 	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:217)
 	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:30)
 	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$InjectionManagerInjectedCdiTarget.inject(CdiComponentProvider.java:680)
 	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:165)
 	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
 	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:104)
 	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
 	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:706)
 	at org.jboss.weld.bean.builtin.InstanceImpl.getBeanInstance(InstanceImpl.java:267)
 	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:116)
 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
 	at jdk.proxy2/jdk.proxy2.$Proxy158.signature(Unknown Source)
 	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:144)
 	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:132)
 	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
 	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300)
 	... 19 more
 Caused by: java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
 	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAnalyzer(ServiceLocatorImpl.java:2468)
 	at org.jvnet.hk2.internal.Utilities.getClassAnalyzer(Utilities.java:143)
 	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:969)
 	... 51 more

**Comment by dmatej** [comment]
Sorry, but I checked your stacktrace and I see you are still not using the latest version 3.1.0 but the old version 3.0.0.

`at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1014)`

**Pull request closed without merging**
