### PR TITLE
Remove unused local variables

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
Just one comments, in many projects the latest copyright is put on top as the first line. Thought I don't think we have any conventions for this.

**Comment by pzygielo** [comment]
> Just one comments, in many projects the latest copyright is put on top as the first line. Thought I don't think we have any conventions for this.

I think chronological order is better in this section, so I follow already established examples
https://github.com/eclipse-ee4j/glassfish-hk2/blob/32868715bc2582e015babb90953df31fc3c3073e/class-model/osgi.bundle#L1-L4

https://github.com/eclipse-ee4j/glassfish-hk2/blob/32868715bc2582e015babb90953df31fc3c3073e/class-model/src/main/java/org/glassfish/hk2/classmodel/reflect/ParsingContext.java#L1-L4

https://github.com/eclipse-ee4j/glassfish-hk2/blob/32868715bc2582e015babb90953df31fc3c3073e/hk2-api/pom.xml#L3-L6

**Comment by dmatej** [comment]
This discussion repeats - I had the same thoughts as you, @pzygielo , but the issue was that the copyright plugin takes the first line. Also I found that in many projects is the newer year first, probably for the same reason, so finally I had to agree with Arjan. 

And another issue - using comma between years is enumerating years in which something new was added. I would prefer rather - character, range. Then it would be perfect :-D  (but currently I don't know how copyright plugin works with that - last changes I did just added the line with 2022)

**Comment by pzygielo** [comment]
> This discussion repeats - I had the same thoughts as you, @pzygielo , but the issue was that the copyright plugin takes the first line.

This should be resolved in the plugin.
It is not used here though.

> And another issue - using comma between years is enumerating years in which something new was added. 

https://www.eclipse.org/projects/handbook/#ip-copyright-headers:
> The date may optionally be set to a range of years with the first and last years of the range separated by a comma (e.g. “2004, 2017”); in this case, the first year is when the content was first created and the last year is when the content was last modified.

**Comment by dmatej** [comment]
> The date may optionally be set to a range of years with the first and last years of the range separated by a comma (e.g. “2004, 2017”); in this case, the first year is when the content was first created and the last year is when the content was last modified.

Hmm, I see this rule as quite problematic and unusual. But it probably doesn't change anything (meaning in relation to laws).

**Comment by arjantijms** [comment]
> This should be resolved in the plugin.

It probably should, too, but at the same time it's still good to have a somewhat standard way of doing this. 

Anyway, it was a just a remark. Don't let it hold up the merge. Just something to think about.

**Pull request merged**
