### PR TITLE
Sync ee4j 8 master

### PR DESCRIPTION
**Pull request by romain-grecourt**
@ankathur FYI.
Let's **NOT** merge this until the release job for HK2 is ready.

This PR will make the master and EE4J_8 branch even.

I have a GF branch ready with the changes required to integrate the next HK2 version, see https://github.com/romain-grecourt/ee4j-glassfish/tree/uptake-latest-hk2

### CODE REVIEW

**Comment by romain-grecourt** [comment]
Note that both branches (EE4J_8 and master) were broken until yesterday...
We should **NOT** have such divergence in these 2 branches without proper ground work. There is no PR automation that ensures the build / tests are passing ; moreover the master branch has the same version of the EE4J_8 branch.

What is breaking the compatibility with EE8 ?
There are a new versions of asm and hibernate-validator, unless I'm mistaking I don't think that breaks EE8 compatiblity.

Let's not carry any more work in the master branch until this project is properly setup.

**Comment by Cousjava** [comment]
@romain-grecourt PRs #394, #409 and #416 all make changes to the apis of HK2. They were all open at least a week, The first one of which was which makes the biggest change was open for a month. If they should not have been merged, then there should have been a review or comment on them to say so.

Also both master and EE4J_8 branches build fine locally without your PRs, master with `mvn clean install` and EE4J_8 with `mvn clean install -Pstaging`.

**Comment by smillidge** [comment]
synching should go from EE4J_8 branch to master not the other way around. The EE4J_8 branch is only for the Eclipse GlassFish release. Initial build pipeline work should be on the EE4J_8 branch then when working changes can be synched over to master.

**Comment by romain-grecourt** [comment]
@Cousjava The build was just broken. HK2 uses a bad trick to build and use the maven-plugins in the same reactor ; if you cleaned-up your maven repo for org/glassfish/hk2 you'd reproduce the error. The issue was related to the rename of org.glassfish.hk2.external:javax.inject to org.glassfish.hk2.external:jakarta.inject. The OSGI adapter tests were also broken because of the same issue.

**Comment by romain-grecourt** [comment]
@smillidge I disagree. Before starting any refactoring work and having such divergence, the build automation should be in-place to prevent any regression from going in. The upcoming merge will only be more difficult.
IMO there is no reason to carry out such refactoring at the moment.

FYI I already did the sync the other way (EE4J_8 -> master).

**Comment by smillidge** [comment]
I agree RE: build automation. Who is going to pick up that work so that tests etc are run from the public jenkins?

**Pull request closed without merging**
